USE [master]
GO

/****** Object:  Database [CreditApproverDb]    Script Date: 27-05-2019 08:46:52 ******/
CREATE DATABASE [CreditApproverDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CreditApproverDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SERVER14\MSSQL\DATA\CreditApproverDb.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CreditApproverDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SERVER14\MSSQL\DATA\CreditApproverDb_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [CreditApproverDb] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CreditApproverDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CreditApproverDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CreditApproverDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CreditApproverDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CreditApproverDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CreditApproverDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [CreditApproverDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CreditApproverDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CreditApproverDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CreditApproverDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CreditApproverDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CreditApproverDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CreditApproverDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CreditApproverDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CreditApproverDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CreditApproverDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CreditApproverDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CreditApproverDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CreditApproverDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CreditApproverDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CreditApproverDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CreditApproverDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CreditApproverDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CreditApproverDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CreditApproverDb] SET  MULTI_USER 
GO

ALTER DATABASE [CreditApproverDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CreditApproverDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CreditApproverDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CreditApproverDb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [CreditApproverDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CreditApproverDb] SET  READ_WRITE 
GO


